// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPhIgxeMuNmqWIWb5yZHQNH2tqdSQ_lAY',
    appId: '1:30093269235:web:1022437db336d1e8dabf86',
    messagingSenderId: '30093269235',
    projectId: 'mini-chat-68b57',
    authDomain: 'mini-chat-68b57.firebaseapp.com',
    storageBucket: 'mini-chat-68b57.firebasestorage.app',
    measurementId: 'G-3E93D2T9GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVSQm7gIvl321O8seDm0lJgo5voKubEGk',
    appId: '1:30093269235:android:4c5a7cca2cf8a930dabf86',
    messagingSenderId: '30093269235',
    projectId: 'mini-chat-68b57',
    storageBucket: 'mini-chat-68b57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnfZCKkrQzcAduAFuid2fqZvEA15pvaJ8',
    appId: '1:30093269235:ios:8e1756051c0d9c1edabf86',
    messagingSenderId: '30093269235',
    projectId: 'mini-chat-68b57',
    storageBucket: 'mini-chat-68b57.firebasestorage.app',
    iosBundleId: 'com.example.miniChat',
  );
}
